### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by cskel** [bytedance/bamboo#1]
Hello,

I've been trying to install BAMBOO on a computing cluster that uses A100s, but I have been encountering some errors. I started by loading some modules that had the required packages (fftw3, cuda, etc). 

I ran init_compile.sh and was able to get the lammps and libtorch code, copy the custom pair files, and append the Torch configuration. (I did adjust this part so that lammps and libtorch are both in the pair folder, so there is ../pair/lammps and ../pair/opt/libtorch, but I adjusted the paths appropriately). 

Then I ran build.sh. I adjusted some of the paths (Is it meant to be CMAKE_PRESETS_PATH="../cmake/presets"? Because there are no instructions to make a cmake folder in the pair folder, so I changed it to CMAKE_PRESETS_PATH="../lammps/cmake/presets" and that worked). I also adjusted the architecture flags (and added "export TORCH_CUDA_ARCH_LIST="8.0 8.6 8.9 9.0"" because at first it gave me an error "Unknown CUDA Architecture Name").  

It started to compile, only to run into these errors: 

pair_bamboo.cpp(278): error: no suitable conversion function from "std::chrono::_V2::system_clock::time_point" to "clock_t" exists
      t_end = std::chrono::high_resolution_clock::now();

pair_bamboo.cpp(281): error: no instance of function template "std::chrono::duration_cast" matches the argument list
            argument types are: (long)
      auto durationInMillis = std::chrono::duration_cast<std::chrono::milliseconds>(t_end - t_start).count();

pair_bamboo.cpp(284): error: no instance of overloaded function "fmt::print" matches the argument list
            argument types are: (const char [44], const char *, int, <error-type>)

pair_bamboo_kokkos.cpp(112): error: expected a ")"
      const int max_neighs_memory = static_cast<int>(1.1f; * d_neighbors.extent(1));

pair_bamboo_kokkos.cpp(112): error: expected a ";"
      const int max_neighs_memory = static_cast<int>(1.1f; * d_neighbors.extent(1));
error: operand of "*" must be a pointer but has type "unsigned long"

      const int max_neighs_memory = static_cast<int>(1.1f; * d_neighbors.extent(1));

pair_bamboo_kokkos.cpp(112): error: operand of "*" must be a pointer but has type "unsigned long"
      const int max_neighs_memory = static_cast<int>(1.1f; * d_neighbors.extent(1));

Do you have any suggestions on what could be the cause of this error? Please let me know if I should supply any additional information.

**Comment by muzhenliang** [comment]
Thank you for highlighting this issue. 

`  const int max_neighs_memory = static_cast<int>(1.1f; * d_neighbors.extent(1));
`  

The error has been addressed in the latest version of the code. Please update your local repository by pulling the latest changes. After updating, I recommend testing the new code to ensure that everything functions correctly on your end. Let us know if you encounter any further issues!
