### ISSUE TITLE
Error at the End of Compiling Lammps with Plugins (Related to Kokkos)

### ISSUE THREAD

**Issue by clecust** [bytedance/bamboo#11]
Hello! 

I'm attempting to compile Lammps with plugins. However, an error occurred at the very end of the compilation process. 
You can check the attached files for the full output record of the compilation process as well as the compilation script. 
It seems that the error message is related to Kokkos. 

Thank you very much for your attention and assistance in advance.

[build.sh](https://github.com/user-attachments/files/18166253/build.sh.log)
[outcuda117.log](https://github.com/user-attachments/files/18166256/outcuda117.log)

**Comment by muzhenliang** [comment]
I've noticed in your log:
Cuda compilation tools, release 11.6, V11.6.124
and
/home/giga/code/lammps-mace-gpu/libtorch-shared-with-deps-1.13.0+cu117/share/cmake/Torch
The version of CUDA and your libtorch don't match. I encountered a similar error when the cuda version was mismatched. So I suspect this is the cause.

**Comment by clecust** [comment]
> I've noticed in your log: Cuda compilation tools, release 11.6, V11.6.124 and /home/giga/code/lammps-mace-gpu/libtorch-shared-with-deps-1.13.0+cu117/share/cmake/Torch The version of CUDA and your libtorch don't match. I encountered a similar error when the cuda version was mismatched. So I suspect this is the cause.

I updated CUDA to version 12.4 and compiled LibTorch (based on PyTorch 2.5.1) locally. Then I successfully compiled LAMMPS and ran the sample LAMMPS script in the benchmark folder. 

Thanks !
