### ISSUE TITLE
Running custom simulation system using BAMBOO

### ISSUE THREAD

**Issue by qiangw001** [bytedance/bamboo#2]
Hello,
  I've been trying to simulate custom liquid systems using BAMBOO. After installation, the demo system runs well with the provided demo data in benchmark subdirectory.
  I'm wondering whether BAMBOO supports building custom simulation systems, such as those created using the "packmol" tool, the current problem is that the input data for BAMBOO-lammps simulation (i.e. \benchmark\in.data) has a field of 'charge' which cannot be simply filled by packmol, it would be great if some tools or instructions can be provided to help running custom systems using BAMBOO.
  b.t.w. You have done a great job. congratulations!

**Comment by muzhenliang** [comment]
We employ a straightforward method to prepare initial files for BAMBOO. Considering that BAMBOO is slower than traditional force fields like OPLS-AA, one can first generate an initial structure with a traditional force field and then perform a short simulation. Utilizing built-in LAMMPS features such as write_data allows for exporting readable structures for machine learning simulations.
