### ISSUE TITLE
How to draw the ssip figure?

### ISSUE THREAD

**Issue by stargolike** [bytedance/bamboo#3]
Hello, dear devoloper.
i read your paper and i want to repeat it. but i can't find the coding how to draw the ssip like this. could you publish the drawing code?
![image](https://github.com/bytedance/bamboo/assets/56385333/89631fec-7278-4adf-bd48-96af46789710)

**Comment by muzhenliang** [comment]
Thank you for your interest. I can explain how to implement it, but I currently don't have plans to open-source this code. First, extract position and charge information from trajectories outputted by LAMMPS, then convert them into numpy format using a Python script. Use empirical rules to identify the structural type of each molecule, group them to tally corresponding charges, and visualize them using matplotlib to generate the images.
If you have experience with Python, you can implement all functionalities similar with ChatGPT-like tools within 1-3 days.
Thank you again for your interest.

**Comment by stargolike** [comment]
> Thank you for your interest. I can explain how to implement it, but I currently don't have plans to open-source this code. First, extract position and charge information from trajectories outputted by LAMMPS, then convert them into numpy format using a Python script. Use empirical rules to identify the structural type of each molecule, group them to tally corresponding charges, and visualize them using matplotlib to generate the images. If you have experience with Python, you can implement all functionalities similar with ChatGPT-like tools within 1-3 days. Thank you again for your interest.

Hello, I am more curious about the specific definitions of SSIP, AGG, and CIP compared to the code. I haven't seen a clear definition in other papers, such as what conditions need to be met to make CIP. If you could provide relevant papers, I would greatly appreciate it.

**Comment by stargolike** [comment]
> Thank you for your interest. I can explain how to implement it, but I currently don't have plans to open-source this code. First, extract position and charge information from trajectories outputted by LAMMPS, then convert them into numpy format using a Python script. Use empirical rules to identify the structural type of each molecule, group them to tally corresponding charges, and visualize them using matplotlib to generate the images. If you have experience with Python, you can implement all functionalities similar with ChatGPT-like tools within 1-3 days. Thank you again for your interest.

Hello, I am more curious about the specific definitions of SSIP, AGG, and CIP compared to the code. I haven't seen a clear definition in other papers, such as what conditions need to be met to make CIP. If you could provide relevant papers, I would greatly appreciate it.

**Comment by stargolike** [comment]
> Thank you for your interest. I can explain how to implement it, but I currently don't have plans to open-source this code. First, extract position and charge information from trajectories outputted by LAMMPS, then convert them into numpy format using a Python script. Use empirical rules to identify the structural type of each molecule, group them to tally corresponding charges, and visualize them using matplotlib to generate the images. If you have experience with Python, you can implement all functionalities similar with ChatGPT-like tools within 1-3 days. Thank you again for your interest.

Hello, I am more curious about the specific definitions of SSIP, AGG, and CIP compared to the code. I haven't seen a clear definition in other papers, such as what conditions need to be met to make CIP. If you could provide relevant papers, I would greatly appreciate it.

**Comment by muzhenliang** [comment]
Here is the information you requested regarding the definitions of SSIP, AGG, and CIP, as found on page 12 of our pre-print paper (https://arxiv.org/pdf/2404.07181):

"In general, the solvation structures can be categorized into SSIP, CIP, and AGG. SSIPs (solvent-separated ion pairs) denote structures composed solely of solvent molecules, in this case, EC and DMC. CIPs (contact ion pairs) represent structures containing one anion-in this context, FSI− within the first solvation shell. Finally, AGGs (aggregates) refer to collective structures composed of more than one anion in the first solvation shell."
