### ISSUE TITLE
Questions regarding the demo data

### ISSUE THREAD

**Issue by kenko911** [bytedance/bamboo#4]
Dear Bamboo Developers,

Thank you very much for the excellent work! I have two questions regarding the demo data and it would be great if you could clarify them.

1. What are the units for the properties such as pos, energy, forces, virial, dipole? I cannot find any relevant information in https://huggingface.co/datasets/mzl/bamboo.

2. I noticed that the demo data has two keys: "cell" and "virial". I assume "virial" here refers to the virial stress, and I found that "cell" has a shape of [203484, 3, 3] with all values being -1. I think we cannot calculate the stress tensor by this and could you please clarify it? Additionally, the demo data contains some structures with non-zero net charge, as indicated by the "total_charge" key. Based on my understanding, the electrostatic energy calculated using Ewald summation for periodic systems with non-zero net charge might not converge. Could you please explain this?

Thank you very much for your help and time. I look forward to your response!

Best
Kenko

**Comment by muzhenliang** [comment]
The units used in Bamboo are the same as the REAL units in LAMMPS. You can find the definition at this URL under the section "For style real, these are the units": https://docs.lammps.org/units.html.

For the training data, we use "cluster" data, which are not periodic boundary conditions (PBC) and contain only several atoms. Therefore, the box is not defined for clusters. We set the box value to -1 as a placeholder to avoid key errors, and it is not used in the training process. The virial is calculated by the definition \(\sum_{i} f_i * r_i\), so it is well-defined even for clusters.

Given that the data are clusters, there is no Ewald summation, so the cluster can have a non-zero net charge.

**Comment by kenko911** [comment]
Dear @muzhenliang,
Thanks a lot for your detailed information!
Best
Kenko
