### ISSUE TITLE
container or RHEL/Centos friendly option

### ISSUE THREAD

**Issue by LinuxPersonEC** [bytedance/bamboo#5]
Any chance there is a container, ideally Apptainer/Singularity? Are there any instructions for installing on RHEL/CentOS/Rocky?

The current installer errors out here:

`./init_compile.sh: line 7: apt-get: command not found`

**Comment by muzhenliang** [comment]
To install the required packages (zip, gfortran, libgtest-dev, libopenblas-dev, and libfftw3-dev) on CentOS, you should use the yum package manager. 

Unfortunately, the container is not available at this time.
