### ISSUE TITLE
Questions about generating training data - Virial tensor and PySCF

### ISSUE THREAD

**Issue by JeongheonSeok** [bytedance/bamboo#6]
I'm trying to generate training data by following the arXiv paper to try out your BAMBOO model myself, but I'm having some difficulties and would like to ask you some questions.

1. How did you specifically calculate the Virial tensor?
I understand that you used PySCF(+gpu4pyscf) to calculate DFT for the cluster, then obtained the pairwise force and the distance vector between atoms from the DFT calculation results, and used them to calculate the Virial tensor.
However, I don't know how you obtained the pairwise force from the DFT results of PySCF. Furthermore, I don't know how to calculate the pairwise force from the general DFT calculation results.
Please let me know how you calculated the pairwise force in this part, or how you obtained the Virial tensor without calculating the pairwise force.

2. How did you calculate D3-CSO with PySCF?
In the paper, you described that you performed all the calculations with PySCF, but I confirmed that PySCF does not support D3-CSO calculations by default.
I wonder you modified the previously uploaded PySCF (https://github.com/pyscf/pyscf) to calculate the D3-CSO calculations, or you first performed the DFT calculation excluding the D3 dispersion and then additionally performed the D3 calculation based on the cluster coordinates.

3. I wonder how you calculated the ChElPG atomic charge with PySCF.
I couldn't find a function to calculate the ChElPG atomic charge in PySCF. I wonder if you used another program or code to calculate the ChElPG atomic charge after the DFT calculation.

Thank you for reading my question. I look forward to your reply.

Have a nice day.

**Comment by muzhenliang** [comment]
1. In cluster data, the virial can be calculated using \( v = \sum_{i} f_i \cdot r_i \). Pairwise data is not necessary.

2. We generate data with GPU4PySCF without D3CSO and add it during inference. For details, see the code here: [GitHub link](https://github.com/bytedance/bamboo/blob/release_202404/models/bamboo_base.py#L142).

3. We fit CHELPG using an independent code to process the original data generated by GPU4PySCF. This code reproduces the algorithm from the original CHELPG paper.

**Comment by JeongheonSeok** [comment]
To muzhenliang.
Thank you for your reply. Despite your kind reply, I have one more question.

According to the calculation formula you provided, v is a scalar value. However, according to the paper and the example dataset, v is a 3x3 rank 2 tensor. Does \cdot in the formula you wrote mean the outer product?

**Comment by muzhenliang** [comment]
The code to calculate virial: np.einsum('ij,ik->jk', pos, forces)

The corresponding formula:
Virial_{jk} = \sum_i {pos}_{ij} * {forces}_{ik}

**Comment by JeongheonSeok** [comment]
I understand. Thank you for your reply.

**Comment by muzhenliang** [comment]
To generate more data for training your model, please contact me at muzhenliang#bytedance.com (replcate # by @ to get email) for assistance with GPU4PySCF usage and home-built workflow. This tool can speed up your process by 10 times and reduce costs by 90%.

**Comment by JeongheonSeok** [comment]
To muzhenliang.
Despite your kind answer, I have one more question.

The virial calculated in the above way is not a symmetric matrix, but I was able to confirm that all the virials of the train data are symmetric matrices.
In addition, when the virial was calculated in the same way using the force and pos data of the train data, it also resulted in an asymmetric matrix. In order to obtain a result similar to the train data, instead of v calculated by v = np.einsum('ij,ik->jk', pos, forces), (v + v.T)/2 was used, and a result similar to the virial of the train data was obtained.
Can I use the asymmetric matrix value as it is for training data? Or can I use the matrix value symmetrized through (v + v.T)/2 like the example train data?

Thank you for reading.

**Comment by Masker-Li** [comment]
> 1. In cluster data, the virial can be calculated using ( v = \sum_{i} f_i \cdot r_i ). Pairwise data is not necessary.
> 
>     2. We generate data with GPU4PySCF without D3CSO and add it during inference. For details, see the code here: [GitHub link](https://github.com/bytedance/bamboo/blob/release_202404/models/bamboo_base.py#L142).
> 
>     3. We fit CHELPG using an independent code to process the original data generated by GPU4PySCF. This code reproduces the algorithm from the original CHELPG paper.


Thank you for the high-quality work, and thank you very much to the developers for answering this confusion. Nevertheless, I have a concern regarding this approach: If we displace a molecule over a certain distance in a specific direction, the forces of the structure are supposed to remain unchanged, and as a result, the virial should also remain constant. But with the calculation based on new pos, I think it's challenging to guarantee that the virial stays the same. How do you think about this?

**Comment by JeongheonSeok** [comment]
> > 1. In cluster data, the virial can be calculated using ( v = \sum_{i} f_i \cdot r_i ). Pairwise data is not necessary.
> >    
> >    2. We generate data with GPU4PySCF without D3CSO and add it during inference. For details, see the code here: [GitHub link](https://github.com/bytedance/bamboo/blob/release_202404/models/bamboo_base.py#L142).
> >    3. We fit CHELPG using an independent code to process the original data generated by GPU4PySCF. This code reproduces the algorithm from the original CHELPG paper.
> 
> Thank you for the high-quality work, and thank you very much to the developers for answering this confusion. Nevertheless, I have a concern regarding this approach: If we displace a molecule over a certain distance in a specific direction, the forces of the structure are supposed to remain unchanged, and as a result, the virial should also remain constant. But with the calculation based on new pos, I think it's challenging to guarantee that the virial stays the same. How do you think about this?


To Masker-Li.
I also had the same problem, so I am leaving a reply in case it helps.

![image](https://github.com/user-attachments/assets/89cd9080-111a-4676-a9d5-aa97337ae2fb)

According to the formula in the attached figure, v is invariant under translation.
So I think you don't have to worry about what you are worried about.

I hope this helps.

**Comment by Masker-Li** [comment]
To JeongheonSeok,
I appreciate your kind reply, it was indeed helpful.

Thanks a lot.
