### ISSUE TITLE
Function of train_data.pt and val_data.pt files

### ISSUE THREAD

**Issue by gullbrekken** [bytedance/bamboo#9]
Hello

This is a general question rather than an issue. I wonder what is the function of the data set, the train_data.pt and val_data.pt files in the huggingface Demo data repository? According to the user manuel, it seems these files are necessary to simulate the electrolyte system. However, only the benchmark.pt file is called in the in.lammps script and I can simulate the system without having these files in my bamboo folder. So what is the purpose and function of these files?

**Comment by muzhenliang** [comment]
The dataset is intended for training a model from scratch, rather than for simulation purposes. It specifically contains EC + LiPF6 clusters, which will be used to develop the model.

**Comment by gullbrekken** [comment]
Thank you for the reply.
